In [2]:
import numpy as np
a = np.array([3, 4])

np.linalg.norm(a)

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
             ])

In [3]:
np.linalg.norm(a)
#求范式，  默认欧氏距离即2范式

5.0

In [4]:
c = np.array([1, 0, 1])

#矩阵与向量相(点)乘
np.dot(b, c)

array([ 4, 10, 16])

In [5]:
np.dot(b.T, c)

array([ 8, 10, 12])

In [7]:
np.dot(c, b.T)

array([ 4, 10, 16])

In [13]:
#求矩阵的迹
np.trace(b)

15

In [17]:
#求行列式
np.linalg.det(b)

-9.5161973539299405e-16

In [19]:
#求矩阵的秩
np.linalg.matrix_rank(b)

2

In [28]:
'''
对正定矩阵求本征值和本征向量
本征值为u，array([ 3.,  1.])
本征向量构成的二维array为v，
array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])
是沿着45°方向
eig()是一般情况的本征值分解，对于更常见的对称实数矩阵，
eigh()更快且更稳定，不过输出的值的顺序和eig()是相反的
'''
d = np.array([
    [2, 1],
    [1, 2]
])

u, v = np.linalg.eig(d)
print(u)
print(v)
u, v = np.linalg.eigh(d)
print(u)
print(v)



[ 3.  1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[ 1.  3.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [29]:
#################
#   numpy随机模块

In [30]:
import numpy as np
import numpy.random as random

In [31]:
#设置随机数种子
random.seed(42)

In [32]:
#产生一个1×3的[0,1)之间的浮点数
random.rand(1, 3)

array([[ 0.37454012,  0.95071431,  0.73199394]])

In [34]:
#产生3×3的[0,1)之间的随机浮点数
print(random.random((3,3)))
print(random.sample((3,3)))
print(random.random_sample((3,3)))
print(random.ranf((3,3)))

[[ 0.83244264  0.21233911  0.18182497]
 [ 0.18340451  0.30424224  0.52475643]
 [ 0.43194502  0.29122914  0.61185289]]
[[ 0.13949386  0.29214465  0.36636184]
 [ 0.45606998  0.78517596  0.19967378]
 [ 0.51423444  0.59241457  0.04645041]]
[[ 0.60754485  0.17052412  0.06505159]
 [ 0.94888554  0.96563203  0.80839735]
 [ 0.30461377  0.09767211  0.68423303]]
[[ 0.44015249  0.12203823  0.49517691]
 [ 0.03438852  0.9093204   0.25877998]
 [ 0.66252228  0.31171108  0.52006802]]


In [36]:
#产生10个[1,6)之间的浮点随机数
print(5*random.random(10)+1)
random.uniform(1, 6, 10)

[ 1.37275322  5.93443468  4.86122385  1.99357841  1.02761059  5.07730714
  4.53428672  4.64503584  4.85635173  1.37022326]


array([ 2.79232864,  1.5793453 ,  5.31551713,  4.11649063,  2.65449012,
        1.31779175,  2.55491161,  2.62591661,  4.64803089,  4.18778736])

In [39]:
#产生10个[1,6)之间的随机整数
random.randint(1, 6, 10)

array([1, 2, 2, 4, 5, 3, 1, 4, 5, 4])

In [40]:
#产生2×5标准正态分布样本
random.normal(size=(2, 5))

array([[-0.21967189,  0.35711257,  1.47789404, -0.51827022, -0.8084936 ],
       [-0.50175704,  0.91540212,  0.32875111, -0.5297602 ,  0.51326743]])

In [47]:
#产生五个， n=5， p=0.5的二项分布样本
#size可以是整数，元组
random.binomial(n=5, p=0.5, size=5)

array([2, 5, 2, 3, 3])

In [48]:
a = np.arange(10)

In [50]:
#从a中有放回随机采样7个
random.choice(a, 7)

array([0, 5, 7, 4, 3, 1, 5])

In [51]:
#从a中无放回采样7个
random.choice(a, 7, replace=False)

array([7, 1, 6, 9, 4, 2, 3])

In [52]:
#对a进行乱序，并返回新的array
b = random.permutation(a)

In [53]:
b


array([7, 1, 4, 0, 5, 3, 8, 6, 9, 2])

In [54]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
#对a进行in-place排序,即直接改变原变量
random.shuffle(a)

In [62]:
a

array([8, 2, 3, 1, 5, 6, 0, 4, 9, 7])

In [63]:
#生成一个长度为9的随机bytes序列作为str返回
random.bytes(9)

b'\xa3\x15\x0c\xc9\xa5\xa5\x07\xe6g'